#include "fuzzpilot/controller/run.hpp"

#include "fuzzpilot/agents/agent_runtime.hpp"
#include "fuzzpilot/config.hpp"
#include "fuzzpilot/env.hpp"
#include "fuzzpilot/ids.hpp"
#include "fuzzpilot/micro/evaluator.hpp"
#include "fuzzpilot/micro/manager.hpp"
#include "fuzzpilot/model/gateway.hpp"
#include "fuzzpilot/mutation/recipe_store.hpp"
#include "fuzzpilot/plateau/detector.hpp"
#include "fuzzpilot/runner/afl_runner.hpp"
#include "fuzzpilot/runner/process.hpp"
#include "fuzzpilot/storage/db.hpp"
#include "fuzzpilot/telemetry/afl_stats.hpp"
#include "fuzzpilot/telemetry/collector.hpp"

#include <algorithm>
#include <chrono>
#include <ctime>
#include <fstream>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <thread>

#include <array>
#include <cctype>
#include <cstdlib>
#include <cstdio>
#include <set>
#include "fuzzpilot/string_util.hpp"


namespace fuzzpilot {
namespace {





std::string json_value_or_raw(const std::string& value) {
  if (value.empty()) {
    return "{}";
  }
  const auto first = value.find_first_not_of(" \t\r\n");
  if (first != std::string::npos && (value[first] == '{' || value[first] == '[')) {
    return value;
  }
  return std::string("{\"raw\":\"") + json_escape(value) + "\"}";
}

void append_line(const std::filesystem::path& path, const std::string& line) {
  std::filesystem::create_directories(path.parent_path().empty() ? "." : path.parent_path());
  std::ofstream output(path, std::ios::app);
  if (!output) {
    throw std::runtime_error("failed to write event log: " + path.string());
  }
  output << line << "\n";
}

void write_text_file(const std::filesystem::path& path, const std::string& content) {
  std::filesystem::create_directories(path.parent_path().empty() ? "." : path.parent_path());
  std::ofstream output(path);
  if (!output) {
    throw std::runtime_error("failed to write file: " + path.string());
  }
  output << content;
}

std::string telemetry_event_json(const std::string& run_id,
                                 const std::string& campaign_id,
                                 const AflStats& stats) {
  return std::string("{\"event\":\"telemetry_tick\",\"run_id\":\"") + json_escape(run_id) +
         "\",\"campaign_id\":\"" + json_escape(campaign_id) + "\",\"stats\":" +
         afl_stats_json(stats) + "}";
}

std::string plateau_blackboard_json(const PlateauEvent& plateau, const AflStats& stats,
                                    const std::string& static_context_json = "{}",
                                    const std::vector<std::string>& recent_decisions = {},
                                    const std::vector<std::string>& memory_entries = {}) {
  std::string history = "[";
  for (size_t i = 0; i < recent_decisions.size(); ++i) {
    history += recent_decisions[i];
    if (i + 1 < recent_decisions.size()) history += ",";
  }
  history += "]";

  std::string memory = "[";
  for (size_t i = 0; i < memory_entries.size(); ++i) {
    memory += memory_entries[i];
    if (i + 1 < memory_entries.size()) memory += ",";
  }
  memory += "]";

  return std::string("{\"plateau\":") + plateau_event_json(plateau) +
         ",\"main_metrics\":" + afl_stats_json(stats) +
         ",\"static_analysis_context\":" + static_context_json +
         ",\"historical_context\":{\"recent_decisions\":" + history +
         ",\"agent_memory\":" + memory + "}" +
         ",\"available_actions\":[\"default_control\",\"dictionary_probe\","
         "\"seed_focus_probe\",\"per_seed_recipe_probe\"]}";
}

std::string run_ida_extractor(const StaticAnalysisConfig& sa_config,
                              const std::filesystem::path& target_binary,
                              const std::filesystem::path& run_dir) {
  const auto output_json = run_dir / "ida_static_context.json";

  const auto result = run_process_capture(
      sa_config.python_bin.string(),
      {sa_config.python_bin.string(),
       sa_config.extractor_script.string(),
       target_binary.string(),
       output_json.string()},
      {{"IDADIR", sa_config.ida_dir.string()}},
      true);
  if (!result.spawned || !result.exited || result.exit_code != 0) {
    return "{\"error\":\"ida_extractor failed\"}";
  }

  std::ifstream ifs(output_json);
  if (!ifs) {
    return "{\"error\":\"ida output not found\"}";
  }
  std::ostringstream ss;
  ss << ifs.rdbuf();
  return ss.str();
}

std::filesystem::path generate_dict_from_ida_json(const std::string& ida_json,
                                                   const std::filesystem::path& run_dir) {
  const auto dict_path = run_dir / "ida_generated.dict";
  std::ofstream dict_out(dict_path);
  if (!dict_out) return {};

  dict_out << "# Auto-generated by FuzzPilot from IDA Pro idalib extraction\n";

  auto decode_json_string = [](const std::string& value) {
    std::string decoded;
    decoded.reserve(value.size());
    bool escaped = false;
    for (const char c : value) {
      if (escaped) {
        switch (c) {
          case 'n': decoded.push_back('\n'); break;
          case 'r': decoded.push_back('\r'); break;
          case 't': decoded.push_back('\t'); break;
          case '\\': decoded.push_back('\\'); break;
          case '"': decoded.push_back('"'); break;
          default: decoded.push_back(c); break;
        }
        escaped = false;
      } else if (c == '\\') {
        escaped = true;
      } else {
        decoded.push_back(c);
      }
    }
    if (escaped) {
      decoded.push_back('\\');
    }
    return decoded;
  };

  auto afl_dict_escape = [](const std::string& value) {
    std::string escaped;
    escaped.reserve(value.size());
    for (const unsigned char c : value) {
      if (c == '\\' || c == '"') {
        escaped.push_back('\\');
        escaped.push_back(static_cast<char>(c));
      } else if (c >= 0x20 && c <= 0x7e) {
        escaped.push_back(static_cast<char>(c));
      }
    }
    return escaped;
  };

  auto should_keep_token = [](const std::string& token) {
    if (token.size() < 3 || token.size() > 24) return false;
    if (token.find("AFL_") == 0 || token.find("__") == 0) return false;
    if (token.find('/') != std::string::npos) return false;
    if (token.find("afl-fuzz") != std::string::npos) return false;
    if (token.find("could not") != std::string::npos) return false;
    return std::all_of(token.begin(), token.end(), [](unsigned char c) {
      return c >= 0x20 && c <= 0x7e;
    });
  };

  // Lightweight string array parsing. The extractor has used both the old
  // extracted_strings key and the newer magic_tokens key across M4 iterations.
  auto extract_array = [&](const std::string& key) -> std::vector<std::string> {
      std::vector<std::string> results;
      auto pos = ida_json.find("\"" + key + "\"");
      if (pos == std::string::npos) return results;
      auto start = ida_json.find('[', pos);
      auto end = ida_json.find(']', start);
      if (start == std::string::npos || end == std::string::npos) return results;

      std::string slice = ida_json.substr(start + 1, end - start - 1);
      std::size_t s_pos = 0;
      while (s_pos < slice.size()) {
          auto q1 = slice.find('"', s_pos);
          if (q1 == std::string::npos) break;
          auto q2 = q1 + 1;
          // Handle escaped quotes
          while (q2 < slice.size() && (slice[q2] != '"' || slice[q2-1] == '\\')) q2++;
          if (q2 >= slice.size()) break;
          results.push_back(decode_json_string(slice.substr(q1 + 1, q2 - q1 - 1)));
          s_pos = q2 + 1;
      }
      return results;
  };

  auto strings = extract_array("magic_tokens");
  auto legacy_strings = extract_array("extracted_strings");
  strings.insert(strings.end(), legacy_strings.begin(), legacy_strings.end());

  std::set<std::string> seen_tokens;
  int token_count = 0;
  for (const auto& token : strings) {
    if (token_count >= 200) break;
    if (!should_keep_token(token)) continue;

    const auto escaped = afl_dict_escape(token);
    if (escaped.empty() || !seen_tokens.insert(escaped).second) continue;

    dict_out << "ida_" << token_count << "=\"" << escaped << "\"\n";
    ++token_count;
  }

  auto process_cmp_constants = [&](const std::string& key) {
    auto pos = ida_json.find("\"" + key + "\"");
    if (pos == std::string::npos) return;
    auto start = ida_json.find('[', pos);
    auto end = ida_json.find(']', start);
    if (start == std::string::npos || end == std::string::npos) return;

    std::string slice = ida_json.substr(start + 1, end - start - 1);
    std::stringstream ss(slice);
    std::string val_str;
    while (std::getline(ss, val_str, ',') && token_count < 250) {
      val_str = std::string(trim(val_str));
      if (val_str.empty()) continue;
      try {
        const uint64_t v = std::stoull(val_str);
        if (v < 0x20202020 || v > 0x7E7E7E7E) continue;

        for (const bool little_endian : {true, false}) {
          std::string decoded;
          for (int i = 0; i < 4; ++i) {
            const int shift = little_endian ? i * 8 : (3 - i) * 8;
            decoded.push_back(static_cast<char>((v >> shift) & 0xff));
          }
          if (!should_keep_token(decoded)) continue;

          const auto escaped = afl_dict_escape(decoded);
          if (escaped.empty() || !seen_tokens.insert(escaped).second) continue;

          dict_out << "ida_cmp_" << token_count++ << "=\"" << escaped << "\"\n";
          if (token_count >= 250) break;
        }
      } catch (...) {
      }
    }
  };

  process_cmp_constants("cmp_constants");
  if (token_count < 250) {
    process_cmp_constants("extracted_cmp_consts");
  }

  return dict_path;
}

std::string coverage_csv_row(const AflStats& stats) {
  return std::to_string(stats.sampled_at) + "," +
         std::to_string(stats.execs_done) + "," +
         std::to_string(stats.execs_per_sec) + "," +
         std::to_string(stats.paths_total) + "," +
         std::to_string(stats.bitmap_cvg) + "," +
         std::to_string(stats.unique_crashes) + "," +
         std::to_string(stats.unique_hangs) + "," +
         std::to_string(stats.recipe_hits) + "," +
         std::to_string(stats.recipe_misses);
}

AflStats read_stats_or_throw(const std::filesystem::path& path) {
  std::string error;
  auto stats = parse_fuzzer_stats(path, &error);
  if (!stats) {
    throw std::runtime_error(error);
  }
  return *stats;
}

std::string normalize_provider_name(std::string provider) {
  for (char& c : provider) {
    if (c == '_') {
      c = '-';
    } else {
      c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    }
  }
  return provider;
}

std::string env_or_fallback(const std::string& env_name, const std::string& fallback) {
  if (!env_name.empty()) {
    if (const char* value = std::getenv(env_name.c_str()); value != nullptr && value[0] != '\0') {
      return value;
    }
  }
  return fallback;
}

std::unique_ptr<IModelGateway> make_gateway(const RunOptions& options, const AppConfig& config) {
  std::string provider;
  if (!options.model_provider.empty()) {
    provider = options.model_provider;
  } else if (!config.model_api.enabled) {
    provider = "fake";
  } else {
    provider = config.model_api.provider;
  }

  provider = normalize_provider_name(provider);
  if (provider.empty() || provider == "fake") {
    return std::make_unique<FakeModelGateway>();
  }

  if (provider == "openai-compatible") {
    const auto endpoint = options.model_endpoint.empty()
                              ? env_or_fallback(config.model_api.endpoint_env,
                                                config.model_api.endpoint)
                              : options.model_endpoint;
    const auto model_name = options.model_name.empty() ? config.model_api.model
                                                       : options.model_name;
    const auto api_key_env = options.api_key_env.empty() ? config.model_api.api_key_env
                                                         : options.api_key_env;
    if (endpoint.empty()) {
      throw std::runtime_error("missing model endpoint for openai-compatible provider");
    }
    if (model_name.empty()) {
      throw std::runtime_error("missing model name for openai-compatible provider");
    }
    if (api_key_env.empty()) {
      throw std::runtime_error("missing api_key_env for openai-compatible provider");
    }
    return std::make_unique<OpenAICompatibleGateway>(endpoint, model_name, api_key_env, true);
  }

  throw std::runtime_error("unsupported model provider: " + provider);
}

void persist_agent_memory(Database& db,
                          const RunSummary& summary,
                          const AppConfig& config,
                          const AgentDecision& decision,
                          double reward_hint) {
  const auto now = static_cast<uint64_t>(std::time(nullptr));

  // Extract specific memory patch if present, else use full proposal
  std::string memory_val = decision.proposal_json;
  const std::string patch_marker = "\"memory_patch\"";
  auto patch_pos = decision.proposal_json.find(patch_marker);
  if (patch_pos != std::string::npos) {
      auto val_start = decision.proposal_json.find(':', patch_pos);
      if (val_start != std::string::npos) {
          // Simple heuristic to extract the value (could be string or object)
          // For real robustness we'd use a JSON parser, but here we stay lightweight
          memory_val = trim(std::string_view(decision.proposal_json).substr(val_start + 1));
          if (!memory_val.empty() && memory_val.back() == '}') memory_val.pop_back();
      }
  }

  const auto key = summary.plateau_id + ":" + decision.agent + ":" +
                   decision.model_response.response_hash;
  const auto evidence = std::string("{\"decision_id\":\"") + json_escape(decision.id) +
                        "\",\"context_hash\":\"" +
                        json_escape(decision.model_response.context_hash) +
                        "\",\"schema_valid\":" +
                        (decision.model_response.schema_valid ? "true" : "false") + "}";
  db.insert_agent_memory(make_id("memory"), summary.run_id, config.target.name, decision.agent,
                         "proposal_memory_patch", key, memory_val, evidence,
                         reward_hint, decision.model_response.schema_valid ? 0.7 : 0.2, now);
  append_line(summary.agent_memory_path,
              std::string("{\"run_id\":\"") + json_escape(summary.run_id) +
                  "\",\"agent\":\"" + json_escape(decision.agent) +
                  "\",\"key\":\"" + json_escape(key) +
                  "\",\"reward_hint\":" + std::to_string(reward_hint) +
                  ",\"memory\":" +
                  json_value_or_raw(memory_val) + "}");
}

void persist_agent_decision(Database& db,
                            RunSummary& summary,
                            const AppConfig& config,
                            const AgentDecision& decision,
                            double reward_hint,
                            const std::filesystem::path& events_path) {
  db.insert_agent_decision(decision);
  ++summary.agent_decision_count;
  append_line(events_path, std::string("{\"event\":\"agent_decision\",\"decision\":") +
                               agent_decision_json(decision) + "}");
  append_line(summary.agent_replay_log_path, agent_decision_json(decision));
  persist_agent_memory(db, summary, config, decision, reward_hint);
}

std::string micro_results_json(const std::vector<MicroResult>& results) {
  std::ostringstream out;
  out << "[";
  for (std::size_t i = 0; i < results.size(); ++i) {
    if (i != 0) {
      out << ",";
    }
    out << micro_result_json(results[i]);
  }
  out << "]";
  return out.str();
}

void write_report(const RunSummary& summary,
                  const AppConfig& config,
                  const std::vector<AflStats>& main_samples,
                  const std::vector<MicroResult>& micro_results,
                  const std::vector<AgentDecision>& decisions) {
  std::filesystem::create_directories(summary.report_path.parent_path());
  std::ofstream report(summary.report_path);
  if (!report) {
    throw std::runtime_error("failed to write report: " + summary.report_path.string());
  }
  report << "# FuzzPilot MVP Run Report\n\n";
  report << "Run ID: `" << summary.run_id << "`\n\n";
  report << "Project: `" << config.project << "`\n\n";
  report << "Target: `" << config.target.name << "`\n\n";
  report << "Plateau ID: `" << summary.plateau_id << "`\n\n";
  report << "Main AFL launch plan: `" << summary.main_launch_path.string() << "`\n\n";
  report << "Main AFL PID: `" << summary.main_pid << "`\n\n";
  report << "Coverage CSV: `" << summary.coverage_csv_path.string() << "`\n\n";
  report << "Agent replay log: `" << summary.agent_replay_log_path.string() << "`\n\n";
  report << "Agent memory: `" << summary.agent_memory_path.string() << "`\n\n";
  report << "Winner intervention: `" << summary.winner_intervention_id << "`\n\n";
  report << "Winner reward: `" << summary.winner_reward << "`\n\n";
  report << "Promoted recipe index: `" << summary.promoted_recipe_index.string() << "`\n\n";
  report << "## Coverage\n\n";
  if (!main_samples.empty()) {
    const auto& first = main_samples.front();
    const auto& last = main_samples.back();
    report << "- samples=`" << main_samples.size() << "` execs_delta=`"
           << (last.execs_done > first.execs_done ? last.execs_done - first.execs_done : 0)
           << "` paths_delta=`"
           << (last.paths_total > first.paths_total ? last.paths_total - first.paths_total : 0)
           << "` crashes=`" << last.unique_crashes << "`\n\n";
  }
  report << "## Agent Decisions\n\n";
  for (const auto& decision : decisions) {
    report << "- `" << decision.agent << "` provider=`" << decision.model_response.provider
           << "` schema_valid=`" << (decision.model_response.schema_valid ? "true" : "false")
           << "` context=`" << decision.model_response.context_hash << "`\n";
  }
  report << "\n## Micro Results\n\n";
  for (const auto& result : micro_results) {
    report << "- `" << result.intervention_id << "` campaign=`" << result.campaign_id
           << "` reward=`" << result.reward << "` new_paths=`" << result.new_paths
           << "` promoted=`" << (result.promoted ? "true" : "false") << "`\n";
  }
}

}  // namespace

RunSummary run_mvp(const RunOptions& options) {
  if (options.config_path.empty()) {
    throw std::runtime_error("RunOptions.config_path is required");
  }
  const auto loaded = load_config(options.config_path);
  const auto& config = loaded.config;

  RunSummary summary;
  summary.run_id = make_id("run");
  summary.main_campaign_id = "main_" + summary.run_id;
  summary.run_dir = options.work_dir / summary.run_id;
  summary.db_path = options.db_path.empty() ? (summary.run_dir / "fuzzpilot.sqlite") : options.db_path;
  summary.report_path = summary.run_dir / "report.md";
  summary.coverage_csv_path = summary.run_dir / "coverage.csv";
  summary.agent_replay_log_path = summary.run_dir / "agent_decisions.jsonl";
  summary.agent_memory_path = summary.run_dir / "agent_memory.jsonl";
  summary.main_launch_path = summary.run_dir / "main_launch.sh";

  std::filesystem::create_directories(summary.run_dir);
  const auto events_path = summary.run_dir / "events.jsonl";
  const auto main_output_dir = summary.run_dir / "main_out";
  const auto main_recipe_store = summary.run_dir / "main_recipes";
  const auto now = static_cast<uint64_t>(std::time(nullptr));

  Database db;
  db.open(summary.db_path);
  db.initialize_schema(options.schema_path);
  const auto env = capture_env_snapshot(config.afl.afl_fuzz.string());
  db.insert_run(summary.run_id, config.project, config.target.name, now, "running",
                env.os, env.arch, env.afl_version);
  db.insert_campaign(summary.main_campaign_id, summary.run_id, "main", "", "",
                     main_output_dir, now,
                     static_cast<uint64_t>(config.afl.main_budget_sec), "running");

  RecipeStore main_store(main_recipe_store);
  main_store.write_compact_recipes({make_default_dictionary_strategy({"FUZZ", "MAGIC", "TOKEN"})});
  const auto main_launch = build_main_afl_spec(config, main_output_dir, main_recipe_store);
  write_text_file(summary.main_launch_path,
                  "#!/usr/bin/env sh\n" + shell_preview(main_launch) + "\n");
  append_line(events_path, std::string("{\"event\":\"main_afl_plan\",\"command\":\"") +
                               json_escape(shell_preview(main_launch)) + "\"}");
  if (!options.dry_run) {
    const auto process = spawn_process(main_launch.afl_fuzz.string(),
                                       main_launch.argv,
                                       main_launch.env);
    if (process.pid < 0) {
      throw std::runtime_error("failed to launch AFL++ main campaign: " + process.error);
    }
    summary.main_pid = process.pid;
    append_line(events_path, std::string("{\"event\":\"main_afl_launched\",\"pid\":") +
                                 std::to_string(summary.main_pid) + "}");
  }

  PlateauConfig plateau_config;
  plateau_config.window_sec = static_cast<uint64_t>(config.afl.plateau_window_sec);
  plateau_config.max_new_paths = static_cast<uint64_t>(std::max(0, config.afl.plateau_min_new_edges));
  plateau_config.min_execs_delta = 1000;
  PlateauDetector detector(plateau_config);

  std::vector<AflStats> main_samples;
  write_text_file(summary.coverage_csv_path,
                  "ts,execs_done,execs_per_sec,paths_total,bitmap_cvg,"
                  "unique_crashes,unique_hangs,recipe_hits,recipe_misses\n");

  auto process_stats = [&](const AflStats& stats) {
    main_samples.push_back(stats);
    db.insert_telemetry(summary.main_campaign_id, stats);
    ++summary.telemetry_count;
    append_line(summary.coverage_csv_path, coverage_csv_row(stats));
    append_line(events_path, telemetry_event_json(summary.run_id, summary.main_campaign_id, stats));
    const auto plateau = detector.add_sample(stats, summary.run_id, summary.main_campaign_id);
    if (plateau && summary.plateau_id.empty()) {
      summary.plateau_id = plateau->id;
      const auto blackboard = plateau_blackboard_json(*plateau, stats);
      db.insert_plateau(*plateau, blackboard);
      append_line(events_path, std::string("{\"event\":\"plateau_detected\",\"plateau\":") +
                                   plateau_event_json(*plateau) + "}");
    }
  };

  // --- Initial Binary Intelligence Scan (M4-Full RE) ---
  std::string base_intelligence_json = "{}";
  if (config.static_analysis.enabled && !config.static_analysis.ida_dir.empty()) {
    const auto intel_path = summary.run_dir / "base_intelligence.json";
    if (!std::filesystem::exists(intel_path)) {
      append_line(events_path, "{\"event\":\"ida_initial_scan_started\"}");
      base_intelligence_json = run_ida_extractor(config.static_analysis,
                                                 std::filesystem::absolute(config.target.binary),
                                                 summary.run_dir);

      const auto raw_ida_path = summary.run_dir / "ida_static_context.json";
      if (std::filesystem::exists(raw_ida_path)) {
        std::filesystem::rename(summary.run_dir / "ida_static_context.json", intel_path);
      } else {
        write_text_file(intel_path, base_intelligence_json);
      }
      append_line(events_path, "{\"event\":\"ida_initial_scan_done\"}");
    } else {
      std::ifstream ifs(intel_path);
      std::ostringstream ss;
      ss << ifs.rdbuf();
      base_intelligence_json = ss.str();
    }
  }

  if (options.dry_run) {
    for (const auto& stats_path : options.main_stats_paths) {
      auto stats = read_stats_or_throw(stats_path);
      process_stats(stats);
    }
  } else {
    TelemetryCollector collector(main_output_dir, "");
    int elapsed_sec = 0;
    while (elapsed_sec < config.afl.main_budget_sec) {
      std::this_thread::sleep_for(std::chrono::seconds(1));
      elapsed_sec += 1;

      std::string error;
      const auto stats = collector.sample(&error);
      if (stats) {
        process_stats(*stats);
        if (!summary.plateau_id.empty()) {
          break; // Stop main loop to evaluate micro-campaigns on plateau
        }
      }
    }
  }

  if (main_samples.empty()) {
    throw std::runtime_error("MVP run requires at least one --stats sample in the current implementation");
  }
  if (summary.plateau_id.empty()) {
    PlateauEvent forced;
    forced.id = make_id("plateau");
    forced.run_id = summary.run_id;
    forced.campaign_id = summary.main_campaign_id;
    forced.detected_ts = static_cast<uint64_t>(main_samples.back().sampled_at);
    forced.window_sec = plateau_config.window_sec;
    forced.reason = "forced_mvp_plateau";
    summary.plateau_id = forced.id;

    const auto recent_decisions = db.get_recent_decisions(summary.run_id, 10);
    const auto agent_memory = db.get_agent_memory(summary.run_id);
    db.insert_plateau(forced, plateau_blackboard_json(forced, main_samples.back(), "{}", recent_decisions, agent_memory));
  }

  const auto snapshot_dir = summary.run_dir / "corpus_snapshot";
  const auto source_output = options.main_afl_output_dir.empty()
                                 ? (options.dry_run ? config.target.input_dir : main_output_dir)
                                 : options.main_afl_output_dir;
  const auto snapshot = snapshot_corpus(source_output, snapshot_dir);
  append_line(events_path, std::string("{\"event\":\"corpus_snapshot\",\"snapshot\":") +
                               corpus_snapshot_json(snapshot) + "}");

  // --- Static Analysis via IDA Pro idalib ---
  std::string static_context_json = "{}";
  std::filesystem::path ida_dict_path;
  if (config.static_analysis.enabled && !config.static_analysis.ida_dir.empty()) {
    append_line(events_path, "{\"event\":\"ida_extractor_started\"}");
    static_context_json = run_ida_extractor(
        config.static_analysis,
        std::filesystem::absolute(config.target.binary),
        summary.run_dir);
    append_line(events_path, std::string("{\"event\":\"ida_extractor_done\",\"context_size\":") +
                                 std::to_string(static_context_json.size()) + "}");

    // Generate AFL++ dictionary from IDA intelligence
    ida_dict_path = generate_dict_from_ida_json(static_context_json, summary.run_dir);
    if (!ida_dict_path.empty() && std::filesystem::exists(ida_dict_path)) {
      append_line(events_path, std::string("{\"event\":\"ida_dict_generated\",\"path\":\"") +
                                   ida_dict_path.string() + "\"}");
    }
  }

  auto gateway = make_gateway(options, config);
  PlateauEvent blackboard_plateau;
  blackboard_plateau.id = summary.plateau_id;
  blackboard_plateau.run_id = summary.run_id;
  blackboard_plateau.campaign_id = summary.main_campaign_id;
  blackboard_plateau.detected_ts = static_cast<uint64_t>(main_samples.back().sampled_at);
  blackboard_plateau.window_sec = plateau_config.window_sec;
  blackboard_plateau.reason = "mvp_blackboard";

  const auto recent_decisions = db.get_recent_decisions(summary.run_id, 20);
  const auto agent_memory = db.get_agent_memory(summary.run_id);

  // Merge plateau-specific context with base intelligence
  std::string combined_intel = base_intelligence_json;
  if (static_context_json != "{}" && static_context_json != base_intelligence_json) {
      combined_intel = static_context_json; // Plateau specific usually has more up-to-date or targeted info
  }

  const auto blackboard = plateau_blackboard_json(blackboard_plateau, main_samples.back(), combined_intel, recent_decisions, agent_memory);
  const auto tasks = make_default_agent_tasks(
      summary.plateau_id, blackboard, static_cast<uint32_t>(config.micro_campaign.budget_sec));
  auto decisions = run_agent_tasks(*gateway, summary.run_id, summary.plateau_id, tasks);
  for (const auto& decision : decisions) {
    persist_agent_decision(db, summary, config, decision, 0.0, events_path);
  }

  const auto specs = plan_micro_campaigns(
      config, summary.plateau_id, snapshot_dir, summary.run_dir / "micro", options.dry_run);
  prepare_micro_campaigns(specs);
  summary.micro_campaign_count = specs.size();

  if (!options.dry_run && summary.main_pid > 0) {
    kill_process(summary.main_pid);
    wait_process(summary.main_pid, 1000);
    append_line(events_path, std::string("{\"event\":\"main_afl_stopped_for_micro\",\"pid\":") +
                                 std::to_string(summary.main_pid) + "}");
    summary.main_pid = -1;
  }

  std::vector<MicroResult> micro_results;
  const auto parent_stats = main_samples.back();
  for (std::size_t i = 0; i < specs.size(); ++i) {
    const auto& spec = specs[i];
    db.insert_campaign(spec.id, summary.run_id, "micro", summary.main_campaign_id,
                       spec.intervention_id, spec.output_dir, now, spec.budget_sec,
                       options.dry_run ? "dry_run" : "running");

    AflStats micro_stats;
    if (options.dry_run) {
      const auto stats_path = options.micro_stats_paths.empty()
                                  ? options.main_stats_paths.back()
                                  : options.micro_stats_paths[std::min(i, options.micro_stats_paths.size() - 1)];
      micro_stats = read_stats_or_throw(stats_path);
    } else {
      const auto micro_launch = build_micro_afl_spec(config, spec, ida_dict_path);
      write_text_file(spec.output_dir / "launch.sh", "#!/usr/bin/env sh\n" + shell_preview(micro_launch) + "\n");
      const auto process = spawn_process(micro_launch.afl_fuzz.string(), micro_launch.argv, micro_launch.env);
      if (process.pid > 0) {
        append_line(events_path, std::string("{\"event\":\"micro_afl_launched\",\"pid\":") +
                                     std::to_string(process.pid) + ",\"campaign_id\":\"" + spec.id + "\"}");
        const auto status = wait_process(process.pid, spec.budget_sec * 1000 + 5000);
        if (!status.exited && !status.signaled) {
          kill_process(process.pid);
          wait_process(process.pid, 1000);
        }
        std::string error;
        auto live_stats = parse_fuzzer_stats(spec.output_dir / "default" / "fuzzer_stats", &error);
        if (live_stats) {
          micro_stats = *live_stats;
        } else {
          micro_stats = parent_stats; // fallback if failed to start/write
        }
      } else {
        micro_stats = parent_stats;
      }
    }
    auto result = evaluate_micro_result(spec.intervention_id, spec.id, parent_stats, micro_stats);
    micro_results.push_back(result);
  }

  if (!micro_results.empty()) {
    auto winner_it = std::max_element(
        micro_results.begin(), micro_results.end(),
        [](const MicroResult& lhs, const MicroResult& rhs) { return lhs.reward < rhs.reward; });
    winner_it->promoted = true;
    summary.winner_intervention_id = winner_it->intervention_id;
    summary.winner_campaign_id = winner_it->campaign_id;
    summary.winner_reward = winner_it->reward;
  }

  for (const auto& result : micro_results) {
    db.insert_micro_result(result);
    db.finish_campaign(result.campaign_id, static_cast<uint64_t>(std::time(nullptr)), "completed");
    append_line(events_path, std::string("{\"event\":\"micro_result\",\"result\":") +
                                 micro_result_json(result) + "}");
  }

  AgentTask result_task;
  result_task.task_id = make_id("agent_task");
  result_task.agent_name = "ResultAnalysisAgent";
  result_task.objective =
      "Summarize validated micro-campaign rewards and produce agent memory patches";
  result_task.blackboard_slice_json =
      std::string("{\"original_blackboard\":") + blackboard +
      ",\"micro_campaign_results\":{\"winner_intervention_id\":\"" +
      json_escape(summary.winner_intervention_id) + "\",\"winner_reward\":" +
      std::to_string(summary.winner_reward) + ",\"all_results\":" +
      micro_results_json(micro_results) + "}}";
  result_task.action_schema_json =
      "{\"allowed_actions\":[\"memory_patch\",\"priority_update\",\"keep_winner\"]}";
  result_task.output_schema_json =
      "{\"required\":[\"agent\",\"memory_patch\",\"critique\"]}";
  result_task.budget_sec = static_cast<uint32_t>(config.micro_campaign.budget_sec);
  const auto result_decisions = run_agent_tasks(
      *gateway, summary.run_id, summary.plateau_id, {result_task});
  for (const auto& decision : result_decisions) {
    persist_agent_decision(db, summary, config, decision, summary.winner_reward, events_path);
    decisions.push_back(decision);
  }

  auto promoted = make_default_dictionary_strategy(
      {"PROMOTED", summary.winner_intervention_id, "FUZZ", "TOKEN"});
  promoted.id = make_id("strategy_promoted");
  RecipeStore promoted_store(summary.run_dir / "promoted_recipes");
  summary.promoted_recipe_index = promoted_store.write_compact_recipes({promoted});
  append_line(events_path, std::string("{\"event\":\"promotion\",\"winner_intervention_id\":\"") +
                               json_escape(summary.winner_intervention_id) +
                               "\",\"recipe_index\":\"" +
                               json_escape(summary.promoted_recipe_index.string()) + "\"}");

  write_report(summary, config, main_samples, micro_results, decisions);

  const auto done = static_cast<uint64_t>(std::time(nullptr));
  db.finish_campaign(summary.main_campaign_id, done, "completed");
  db.finish_run(summary.run_id, done, "completed");

  if (!options.dry_run && summary.main_pid > 0) {
    kill_process(summary.main_pid);
    wait_process(summary.main_pid, 1000);
  }

  return summary;
}

std::string run_summary_json(const RunSummary& summary) {
  std::ostringstream out;
  out << "{";
  out << "\"run_id\":\"" << json_escape(summary.run_id) << "\",";
  out << "\"main_campaign_id\":\"" << json_escape(summary.main_campaign_id) << "\",";
  out << "\"plateau_id\":\"" << json_escape(summary.plateau_id) << "\",";
  out << "\"winner_intervention_id\":\"" << json_escape(summary.winner_intervention_id) << "\",";
  out << "\"winner_campaign_id\":\"" << json_escape(summary.winner_campaign_id) << "\",";
  out << "\"winner_reward\":" << summary.winner_reward << ",";
  out << "\"run_dir\":\"" << json_escape(summary.run_dir.string()) << "\",";
  out << "\"db_path\":\"" << json_escape(summary.db_path.string()) << "\",";
  out << "\"report_path\":\"" << json_escape(summary.report_path.string()) << "\",";
  out << "\"coverage_csv_path\":\"" << json_escape(summary.coverage_csv_path.string()) << "\",";
  out << "\"agent_replay_log_path\":\"" << json_escape(summary.agent_replay_log_path.string()) << "\",";
  out << "\"agent_memory_path\":\"" << json_escape(summary.agent_memory_path.string()) << "\",";
  out << "\"main_launch_path\":\"" << json_escape(summary.main_launch_path.string()) << "\",";
  out << "\"promoted_recipe_index\":\"" << json_escape(summary.promoted_recipe_index.string()) << "\",";
  out << "\"telemetry_count\":" << summary.telemetry_count << ",";
  out << "\"agent_decision_count\":" << summary.agent_decision_count << ",";
  out << "\"micro_campaign_count\":" << summary.micro_campaign_count << ",";
  out << "\"main_pid\":" << summary.main_pid;
  out << "}";
  return out.str();
}

}  // namespace fuzzpilot
